# Generated by Django 4.1.3 on 2022-11-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("name_from_form", models.CharField(max_length=50)),
                (
                    "user_gender",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "man"), (2, "woman")]
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "start_form"),
                            (2, "main_menu"),
                            (3, "recipe_menu"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["username"],
            },
        ),
    ]
