# Generated by Django 4.1.3 on 2022-11-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Recipe", new_name="User",),
    ]
