# Generated by Django 4.1.3 on 2022-11-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_users", "0002_rename_recipe_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
