# Generated by Django 4.1.3 on 2022-11-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_users", "0003_alter_user_user_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="user_state",),
    ]
