# Generated by Django 4.1.3 on 2022-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_users", "0004_remove_user_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_state",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "start_form"), (2, "main_menu"), (3, "recipe_menu")],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
