# Generated by Django 4.1.3 on 2022-11-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_users", "0005_user_user_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
