# Generated by Django 4.1.3 on 2022-11-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "photo",
                    models.ImageField(height_field=100, upload_to="images/recipes"),
                ),
                ("description", models.TextField()),
            ],
            options={"verbose_name": "Recipe", "verbose_name_plural": "Recipes",},
        ),
    ]
