# Generated by Django 4.1.3 on 2022-11-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(
                height_field="height", upload_to="images/recipes", width_field="width"
            ),
        ),
    ]
