# Generated by Django 4.1.3 on 2022-11-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["name"],
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
    ]
