# Generated by Django 4.1.3 on 2022-11-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/recipes"),
        ),
    ]
