# Generated by Django 4.1.3 on 2022-11-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="user_state",),
    ]
