# Generated by Django 4.1.3 on 2022-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0003_user_user_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name_from_form",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_gender",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "man"), (2, "woman")], null=True
            ),
        ),
    ]
