# Generated by Django 4.1.3 on 2022-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0005_alter_user_user_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_state",
            field=models.CharField(
                choices=[
                    ("start_form", "start_form"),
                    ("main_menu", "main_menu"),
                    ("recipe_menu", "recipe_menu"),
                ],
                max_length=20,
            ),
        ),
    ]
