# Generated by Django 4.1.3 on 2022-11-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0006_alter_user_user_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_state",
            field=models.CharField(
                choices=[
                    ("name_form", "name_form"),
                    ("gender_form", "gender_form"),
                    ("main_menu", "main_menu"),
                    ("recipe_menu", "recipe_menu"),
                ],
                max_length=20,
            ),
        ),
    ]
